spring:
  name: DemoAnnotationStarter
  kafka:
    bootstrap-servers: 192.168.3.155:9092
    #bootstrap-servers: 192.168.43.48:9092
    topic:
      metrics: t1_demo_metrics
    consumer:
      group-id: t1-demo


  datasource:
    #url: jdbc:postgresql://192.168.3.155:5432/t1_demo
    url: jdbc:postgresql://192.168.43.48:5432/t1_demo
    username: "postgres"
    password: "123"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    contexts: starter
annotation:
  logging:
    enabled: true